In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.image as image
import glob
import os

In [ ]:
images_fp ='/content/drive/MyDrive/my projects/images'

In [ ]:
image_names=[os.path.basename(file) for file in glob.glob(os.path.join(images_fp,'*.jpg'))]

In [ ]:
image_names

['Abyssinian_213.jpg',
 'Bengal_30.jpg',
 'Birman_170.jpg',
 'Birman_185.jpg',
 'Birman_174.jpg',
 'Birman_200.jpg',
 'Birman_201.jpg',
 'Birman_199.jpg',
 'Bombay_128.jpg',
 'Bombay_185.jpg',
 'Bombay_188.jpg',
 'Bombay_189.jpg',
 'Bombay_192.jpg',
 'Bombay_193.jpg',
 'Bombay_186.jpg',
 'Bombay_190.jpg',
 'Bombay_4.jpg',
 'Bombay_214.jpg',
 'Bombay_208.jpg',
 'Bombay_204.jpg',
 'Bombay_206.jpg',
 'Bombay_210.jpg',
 'Bombay_2.jpg',
 'Bombay_198.jpg',
 'Bombay_217.jpg',
 'Bombay_205.jpg',
 'Bombay_220.jpg',
 'Bombay_203.jpg',
 'Bombay_201.jpg',
 'Bombay_221.jpg',
 'Bombay_3.jpg',
 'Bombay_202.jpg',
 'Bombay_5.jpg',
 'British_Shorthair_2.jpg',
 'British_Shorthair_278.jpg',
 'British_Shorthair_6.jpg',
 'British_Shorthair_3.jpg',
 'american_bulldog_158.jpg',
 'basset_hound_85.jpg',
 'beagle_18.jpg',
 'boxer_10.jpg',
 'boxer_1.jpg',
 'boxer_11.jpg',
 'boxer_15.jpg',
 'boxer_12.jpg',
 'boxer_13.jpg',
 'boxer_14.jpg',
 'boxer_16.jpg',
 'boxer_4.jpg',
 'boxer_200.jpg',
 'boxer_5.jpg',
 'boxer_

In [ ]:
labels= [' '.join(name.split('_')[:-1:]) for name in image_names]

In [ ]:
labels

['Abyssinian',
 'Bengal',
 'Birman',
 'Birman',
 'Birman',
 'Birman',
 'Birman',
 'Birman',
 'Bombay',
 'Bombay',
 'Bombay',
 'Bombay',
 'Bombay',
 'Bombay',
 'Bombay',
 'Bombay',
 'Bombay',
 'Bombay',
 'Bombay',
 'Bombay',
 'Bombay',
 'Bombay',
 'Bombay',
 'Bombay',
 'Bombay',
 'Bombay',
 'Bombay',
 'Bombay',
 'Bombay',
 'Bombay',
 'Bombay',
 'Bombay',
 'Bombay',
 'British Shorthair',
 'British Shorthair',
 'British Shorthair',
 'British Shorthair',
 'american bulldog',
 'basset hound',
 'beagle',
 'boxer',
 'boxer',
 'boxer',
 'boxer',
 'boxer',
 'boxer',
 'boxer',
 'boxer',
 'boxer',
 'boxer',
 'boxer',
 'boxer',
 'boxer',
 'boxer',
 'boxer',
 'boxer',
 'boxer',
 'boxer',
 'boxer',
 'boxer',
 'boxer',
 'boxer',
 'boxer',
 'boxer',
 'EgyptianMau',
 'EgyptianMau',
 'americanpitbullterrier']

In [ ]:
set(labels)

{'Abyssinian',
 'Bengal',
 'Birman',
 'Bombay',
 'British Shorthair',
 'EgyptianMau',
 'american bulldog',
 'americanpitbullterrier',
 'basset hound',
 'beagle',
 'boxer'}

In [ ]:
def label_encode(label):
  if label=='Bengal': return 0
  elif label=='Birman':return 1
  elif label=='Bombay':return 2
  elif label=='British Shorthair':return 3
  elif label=='american bulldog':return 4
  elif label=='basset hound':return 5
  elif label=='beagle':return 6
  elif label=='boxer':return 7
  elif label=='EgyptianMau':return 8


In [ ]:
import tensorflow as tf
from tensorflow.keras.preprocessing.image import load_img,img_to_array

In [ ]:
features = []
labels = []
image_size = (224,224)

for name in image_names:
    label =' '.join(name.split('_')[:-1:])
    label_encoded= label_encode(label)

    if label_encoded != None:
      img=load_img(os.path.join(images_fp, name))
      img= tf.image.resize_with_pad (img_to_array(img, dtype='uint8'), *image_size).numpy().astype('uint8')
      image= np.array(img)

      features.append(image)
      labels.append(label_encoded)

In [ ]:
len(labels)

In [ ]:
 features_array= np.array(features)
 labels_array= np.array(labels)

In [ ]:
features_array

array([[[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        ...,

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]],


       [[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0,

In [ ]:
labels_array

array([0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 5, 6, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8])

In [ ]:
labels_one_hot =pd.get_dummies(labels_array)

In [ ]:
labels_one_hot

0  1  2  3  4  5  6  7  8
0   1  0  0  0  0  0  0  0  0
1   0  1  0  0  0  0  0  0  0
2   0  1  0  0  0  0  0  0  0
3   0  1  0  0  0  0  0  0  0
4   0  1  0  0  0  0  0  0  0
.. .. .. .. .. .. .. .. .. ..
60  0  0  0  0  0  0  0  1  0
61  0  0  0  0  0  0  0  1  0
62  0  0  0  0  0  0  0  1  0
63  0  0  0  0  0  0  0  0  1
64  0  0  0  0  0  0  0  0  1

[65 rows x 9 columns]

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(features_array,labels_one_hot,test_size=0.2,random_state=42)

In [ ]:
X_train,X_val,y_train,y_val=train_test_split(X_train,y_train,test_size=0.25,random_state=1)

In [ ]:
from tensorflow.keras  import layers, Input, Model
from tensorflow.keras.models import Sequential
from tensorflow.keras.applications import ResNet50
from tensorflow.keras.applications.resnet50 import preprocess_input as pp_i
from tensorflow.keras.layers import RandomRotation, RandomFlip, Dense, Dropout
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.losses import CategoricalCrossentropy
from keras.models import Model
from keras.layers import Dense

In [ ]:
data_augmentation=Sequential([RandomFlip("horizontal_and_vertical"), RandomRotation(0.2)])

In [ ]:
predict_layers= Dense(9,activation='softmax')

In [ ]:
resnet_model = ResNet50(include_top=False, pooling='avg', weights = 'imagenet')
resnet_model.trainable = False
preprocess_input = pp_i

94765736/94765736 [==============================] - 1s 0us/step


In [ ]:
# Build model
inputs=Input(shape=(224,224,3))
x = data_augmentation(inputs)
x = preprocess_input(x)
x = resnet_model(x, training = False)
x = Dropout(0.2)(x)
outputs= predict_layers(x)
model=Model(inputs, outputs)

In [ ]:
model.summary()

NameError: ignored

In [ ]:
model.compile(optimizer=Adam(),loss=CategoricalCrossentropy(), metrics=['accuracy'])

In [ ]:
model_history=model.fit(X_train,y_train,validation_data=(X_val,y_val),epochs=5)

Epoch 1/5
2/2 [==============================] - 19s 8s/step - loss: 2.4329 - accuracy: 0.3590 - val_loss: 1.8520 - val_accuracy: 0.4615
Epoch 2/5
2/2 [==============================] - 9s 4s/step - loss: 1.4619 - accuracy: 0.5128 - val_loss: 1.5917 - val_accuracy: 0.5385
Epoch 3/5
2/2 [==============================] - 11s 4s/step - loss: 1.0100 - accuracy: 0.6667 - val_loss: 1.5232 - val_accuracy: 0.6923
Epoch 4/5
2/2 [==============================] - 11s 3s/step - loss: 1.0471 - accuracy: 0.7179 - val_loss: 1.4387 - val_accuracy: 0.6923
Epoch 5/5
2/2 [==============================] - 12s 7s/step - loss: 0.7222 - accuracy: 0.8205 - val_loss: 1.3316 - val_accuracy: 0.6923


In [ ]:
model.evaluate(X_test,y_test)

1/1 [==============================] - 2s 2s/step - loss: 1.5318 - accuracy: 0.6923


[1.5318270921707153, 0.692307710647583]

In [ ]:
acc =model_history.history['accuracy']
val_acc=model_history.history['val_accuracy']
loss=model_history.history['loss']
val_loss=model_history.history['val_loss']

In [ ]:
epochs_range =range(5)
plt.figure(figsize=(15,8))

plt.subplot(1,2,1)
plt.plot(epochs_range,acc,label='Training accuracy')
plt.plot(epochs_range,val_acc,label='Validation accuracy')
plt.legend(loc='lower right')
plt.title('Training and Validation accuracy')

plt.subplot(1,2,2)
plt.plot(epochs_range,loss,label='Training loss')
plt.plot(epochs_range,val_loss,label='Validation loss')
plt.legend(loc='upper right')
plt.title('Training and Validation loss')

NameError: ignored

In [ ]:
model.evaluate(X_test, y_test)

NameError: ignored

In [ ]:
y_pred= model.predict(X_test)

1/1 [==============================] - 3s 3s/step


In [ ]:
y_pred

array([[2.49108329e-04, 2.50936039e-02, 1.43220648e-01, 2.68729869e-02,
        1.78561453e-02, 4.72149858e-03, 3.02214088e-04, 7.75390983e-01,
        6.29283162e-03],
       [2.26934280e-04, 3.06738056e-02, 3.44325565e-02, 3.91868968e-03,
        4.52098018e-03, 5.27242664e-03, 2.37187473e-04, 9.19652522e-01,
        1.06493442e-03],
       [1.78622449e-05, 6.71843439e-03, 8.44112992e-01, 1.05481967e-03,
        9.15874902e-04, 2.32923729e-03, 8.50149809e-06, 1.44784629e-01,
        5.77261671e-05],
       [1.45538143e-04, 4.20126952e-02, 2.08315298e-01, 9.35278833e-03,
        7.27244001e-03, 3.07589467e-03, 4.87696343e-05, 7.29396880e-01,
        3.79771402e-04],
       [2.88939173e-05, 3.32738042e-01, 5.98306060e-01, 2.62555759e-02,
        1.16208347e-03, 7.96906417e-04, 4.59299452e-04, 3.90432999e-02,
        1.20978127e-03],
       [2.06607700e-04, 3.28171737e-02, 7.32209533e-02, 8.82098917e-03,
        4.44127852e-03, 2.25056964e-03, 5.45816671e-04, 8.74549329e-01,
        3.1